### ISSUE TITLE
"See nearby buildings" error

### ISSUE THREAD

**Issue by meetar** [polygon-city/polygon-city-app#114]
Unable to use "See nearby buildings" link on building pages, eg this link: http://dev.polygon.city/search/near/13.4089714,52.5209055,1000

Produces a page with this error:
{"name":"MongoError","message":"n/a","$err":"Unable to execute query: error processing query: ns=building-database.buildings limit=7 skip=0\nTree: $and\n    hidden == false\n    GEONEAR  field=location maxdist=1000 isNearSphere=0\nSort: {}\nProj: {}\n planner returned error: unable to find index for $geoNear query","code":17007}

**Comment by robhawkes** [comment]
Interesting. I wonder if the geospatial index has been removed somehow:

```
db.buildings.ensureIndex( { location: "2dsphere" } );
```

If someone can remotely access the database then it should be easy enough to check the indexes via a GUI tool, otherwise you can list the indexes from the command-line by running:

```
db.buildings.getIndexes();
```

**Comment by meetar** [comment]
db.buildings.ensureIndex( { location: "2dsphere" } );

Yep – this fixed it.
