### ISSUE TITLE
Leaflet cluster marker too small for >10K 

### ISSUE THREAD

**Issue by meetar** [polygon-city/polygon-city-app#119]
<img width="164" alt="screen shot 2015-09-12 at 10 04 43 am" src="https://cloud.githubusercontent.com/assets/459970/9831869/d865a4ac-5935-11e5-87b2-ca79280303b9.png">

A good problem to have :)

**Comment by robhawkes** [comment]
Pushed 15d970a which should improve this – basically any markers that represent a lot of items will now display a bit bigger and should fit the number.

![](http://cl.ly/image/1D050Q2Q0D0s/Screen%20Shot%202015-09-25%20at%2013.55.13.png)
