### ISSUE TITLE
Speed up /browse/all endpoint

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/polygon-city-app#128]
An interim measure for speeding up `/browse/all` needs to be found until #82 arrives.

Currently, all buildings are retrieved and served to `/browse/all` on load, causing a long and visible delay now that we have many thousands of buildings.

Eventually, a much more advanced system will be put in place that dynamically updates the map and only requests the data that's needed – this is for v2.

Until then, something more lightweight needs to be implemented that doesn't require rewriting the client-side mapping logic nor the server-side logic.

The solution that jumps to mind is to remove all the chunky data from the initial page-load (eg. everything bar the lat/lon points) and implement a new endpoint to request that extra data only when a building is clicked on the map. This should dramatically speed up the initial page load enough until we revisit this in v2.

**Comment by meetar** [comment]
Agreed – browse/all seems to be unreachable at this time. db has about 100K buildings.

**Comment by robhawkes** [comment]
I've pushed what I thought would improve the situation (it does for amounts in the low tens of thousands) but it seems that we have so many buildings that querying them all and manipulating that result is taking so long it's timing out the request.

Looks like this may require something more advanced. We can save a lot of time and effort by limiting the zoom so we can limit the number of buildings in view – I'll take a stab at that next. It's not perfect but it's a good compromise until we properly revisit this in v2.

**Comment by robhawkes** [comment]
I've pushed a new approach that is fully dynamic, though not very intelligent. It does the job though and `/browse/all` is accessible again on the dev server. We can neaten up this approach in v2 when we implement something more robust.
