### ISSUE TITLE
ENOTDIR error on upload

### ISSUE THREAD

**Issue by meetar** [polygon-city/polygon-city-app#132]
When attempting to upload a building with the building-database-obj-importer, every building fails with eg:

    body: '{"error":"ENOTDIR, rename \'tmp/tmp/31691455c3eb3c98d241c7ad2136e35e.obj\'"}'

**Comment by robhawkes** [comment]
Ah, this'll be because of the new config option to define the temporary directory for storing uploads and converted files.

I'll have a look into what's been defined on the dev server and see what I can replicate locally. Hopefully it's as simple as updating the path.

**Comment by robhawkes** [comment]
So this was a problem with the new config option for temporary directories, though an edge-case for when the config option is specifically set to `./tmp/`. This was actually conflicting with a naive split performed on the directory string of the uploaded file using the string "tmp/" – I've made it a little more robust and fixed this particular issue.

**Comment by robhawkes** [comment]
We should be good on the dev server now – I just tested a manual upload and it works now, rather than spitting the `ENOTDIR` error.
