### ISSUE TITLE
Add a method to import buildings in bulk

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/polygon-city-app#39]
It's clear that we'll eventually need some method to process a large number of buildings in an automated fashion. Everything from upload, conversion and addition to the database will need to be automated. This would likely only be an internal tool.

This approach means that the normal Web-based method of adding buildings won't be suitable and it'll likely need to be a command-line tool / local script of some sort.

Things to consider:
- The location of each building will need to be detected and added automatically (likely coming from a separate metadata file)

**Comment by robhawkes** [comment]
I've been looking into this and it's clear that to make sure it's implemented correctly we're going to need a sample bulk dataset to use. I'm continuing to look into this though I don't have anything solid yet.

**Comment by meetar** [comment]
In the most simple case we could use an OSM extract and just upload the same basic model for each building.

**Comment by robhawkes** [comment]
Ok, that works. I'll just convert some OSM data into a format we could likely expect to ask for (eg. KML, CSV or a geodatabase) and build an importer around that.

**Comment by meetar** [comment]
Would any of our metro extract formats be an easy starting point? https://mapzen.com/metro-extracts/

**Comment by meetar** [comment]
So after a little discussion with @bcamper it seems as though starting with a metro extract (or OSM data in general) may not be worth the effort, particularly since most bulk imports are unlikely to be 2D shapefiles. So it might be better to find a dataset we'd actually want to import to test the upload process, and if we want to test the capabilities of the db/UI it might be simplest to just upload a selection of models and then dupe them in the db. Thoughts?

**Comment by robhawkes** [comment]
Oh I was assuming just using the OSM extract to get real building locations and then converting that into something more likely (eg. KML) and uploading a fake identical model for each one rather than use the flat polygon for anything. I think that could work anyway, even if that's not what you meant.

**Comment by meetar** [comment]
That's what I'd been thinking, and if it's useful to do then by all means
feel free!

**Comment by robhawkes** [comment]
With the [new batch importers](https://github.com/polygon-city/building-database-obj-importer) and [CityGML converters](https://github.com/polygon-city/citygml-to-obj), things have changed a lot since this issue was created so I'm going to close it. Happy to re-open it should we decide to revisit it!
