### ISSUE TITLE
CityGML conversion

### ISSUE THREAD

**Issue by meetar** [polygon-city/polygon-city-app#85]
Consider bulk CityGML imports and conversions

**Comment by robhawkes** [comment]
Being XML, we could read it directly if we fancy building out the logic to generate the 3D geometry from the string definitions. Otherwise, we can pass it through [CityGMLtoOBJs](https://github.com/tudelft3d/CityGML2OBJs) to convert it into an OBJ format. The issue with the second approach (if you can call it an issue) is that we'd have to re-run that every time the CityGML data is updated.

**Comment by meetar** [comment]
The latter would be simpler for a first pass, if that's onerous we can
always do something more complex later. Regardless we'll need to consider
versions: #84

**Comment by robhawkes** [comment]
I gave this a go yesterday and there seems to be an issue with some of the CityGML feeds I'm using. The converter only accepts version 2.0 of CityGML and a lot of cities are still using 1.0. Fortunately, the difference isn't vast (it's just XML) so we can probably work out a way to upgrade to the 2.0 schema.

Another issue I bumped into is that the CityGML produced by some cities seems to include invalid geometry and so doesn't convert to OBJ. I need to look into that further as it may just be a result of my lack of understanding with this data format.

**Comment by robhawkes** [comment]
I'm still not much further with this. I gave FME a go but that was mega confusing and not really a long-term solution. I also looked into [3DCityDB](http://www.3dcitydb.org/) which looks promising but I couldn't get it to validate any of my CityGML files, nor connect to a PostGIS database.

CityGML2OBJs is definitely the most useful from our perspective (as we could run it on a server) but I've not yet worked out why it errors out on the CityGML files that I'm using ([I've filed a bug](https://github.com/tudelft3d/CityGML2OBJs/issues/2) in the hope of more insight).

**Comment by robhawkes** [comment]
I had another round with CityGML today and we're beginning to understand each other. I'm now able to import CityGML files into a PostGIS database using 3DCityDB and then export the individual buildings back out as collada files or raw geometry (both within a KMZ – so attached to real-world positions). Theoretically, this is enough to act as the base for an import, assuming we are happy with the building LOD (even a high LOD building in CityGML can actually just be a box if the roof and other attributes aren't defined).

Here's an example building collada from a CityGML dataset of Linz, Austria:

![](http://cl.ly/image/0Q1F180i3K2S/Screen%20Shot%202015-03-04%20at%2010.14.47.png)

**Comment by meetar** [comment]
Excellent – excited to see what a large-scale import looks like :)

**Comment by robhawkes** [comment]
Annoyingly, 3DCityDB seems to export the collada files with a broken materials definition which screws up the output in other applications (eg. flipped normals). For an automated process we'll need to fix these (assuming it happens for all exports from all cities). I've found a couple of approaches that work, specifically;

- Opening the collada in Meshlab and re-exporting it as a collada with the "Normal" checkbox selected
- Opening the collada in SketchUp and flipping the normals for all faces, then exporting back out

**Comment by robhawkes** [comment]
Ok, so I've made some good progress today. We can now run a little import script that takes an exported CityGML KML and runs a batch upload to Polygon City. In theory it should just work, though in practice there seems to be some bugs to iron out as not all the models seem to convert properly.

Next week will be fun as this process is improved!

![](http://cl.ly/image/1l261418441t/Screen%20Shot%202015-03-06%20at%2013.48.06.png)
![](http://cl.ly/image/2v0w160e1y0V/Screen%20Shot%202015-03-06%20at%2013.47.14.png)

**Comment by robhawkes** [comment]
I've managed to fix the errors and get an example CityGML dataset to add to my local Polygon City instance (100 buildings). I'm currently downloading the entirety of Linz, Austria right now to see what a whole city looks like. I may have a couple of issues as I'm not even finished yet and the CityGML files have surpassed 800MB. My Internet is appalling here so I likely won't be able to upload everything – I'll select a large-enough area at least to get an idea of what a city might look like.

![](http://cl.ly/image/1U2d1n3m0K1r/Screen%20Shot%202015-03-09%20at%2011.52.13.png)

**Comment by robhawkes** [comment]
Currently 1/2-way through uploading a 4,000 building sample from Linz. Slow (due to my Internet) but on the plus side I now know that the site seems to cope ok with a huge batch upload happening at the same time as people trying to use the site.

One thing I did notice is that while the individual building models seem correct and seem to render ok, if I provide them via an aggregated KML the result is horrific (broken polygons, duplicated building models even though all are different, etc). I'm wondering if this is a manifestation of the collada issues in Three.js (so maybe fixed by moving to OBJ) or wether it's a problem with my implementation of the aggregated KML.

**Comment by robhawkes** [comment]
That's a whole lotta buildings, and it's only a fraction of what's available for Linz! The polygon count is off for some reason, which I need to look into.

![](http://cl.ly/image/2f391u2T1u2w/Screen%20Shot%202015-03-10%20at%2010.33.57.png)
![](http://cl.ly/image/1K1N3P1Y0I3x/Screen%20Shot%202015-03-10%20at%2010.34.35.png)
![](http://cl.ly/image/33112E2x3F2J/Screen%20Shot%202015-03-10%20at%2010.35.57.png)

**Comment by bcamper** [comment]
Awesome progress!

UUID_879D955A is one of my favorite buildings.

**Comment by meetar** [comment]
Looking good! I notice that building preview looks centered on the model, too :)

**Comment by robhawkes** [comment]
I'm more a fan of UUID_916E8034 – it has a certain something about it ;)

@meetar: Unfortunately that wasn't deliberate, though I'm looking at how to best achieve this. I think I'm most of the way to a theoretical solution now.

**Comment by robhawkes** [comment]
I've pushed the importer script with instructions to https://github.com/polygon-city/building-database-kml-importer. I'm unsure if I did anything outside of those instructions so let me know how you get on and we can tweak them.

Also, please add issues in that repo should you have any trouble or see specific errors. No doubt we'll start seeing some as we test this beyond my local setup (now working for Lyon, Montreal and Linz!)

![](http://cl.ly/image/1l1t211t2N0j/Screen%20Shot%202015-03-13%20at%2012.14.28.png)
![](http://cl.ly/image/2e0x3I271R1S/Screen%20Shot%202015-03-13%20at%2012.15.14.png)

**Comment by robhawkes** [comment]
I've now tried importing subsets of all the CityGML sources listed in this issue. The general feeling is good, though some cities are clearly better than others – both in model validity and detail. Unfortunately, some cities clearly haven't validated their CityGML geometry and so models either don't export, or have nasty quirks such as missing faces, etc. Also, Lyon is potentially unusable right now as all the buildings in a city block are represented as a single model (it's possible we could split them).

Here's a selection of what we have so far (on my local setup):
![](http://cl.ly/image/1i3l111G1c0p/Screen%20Shot%202015-03-18%20at%2008.28.23.png)

An example from Rotterdam:
![](http://cl.ly/image/1N1f311n0z1c/Screen%20Shot%202015-03-18%20at%2008.28.44.png)

An example from Lyon:
![](http://cl.ly/image/3y2A1D1m3E2Q/Screen%20Shot%202015-03-18%20at%2008.39.02.png)

**Comment by robhawkes** [comment]
The latest improvements to the KML importer mean that we have 100% coverage on valid CityGML areas now. This is just one tiny snapshot of the 550,000 buildings that Berlin released (there's no way I can upload that many for testing on this connection!).

![](http://cl.ly/image/1U1t0D1N1K0a/Screen%20Shot%202015-03-25%20at%2014.58.57.png)

**Comment by bcamper** [comment]
Amazing! Very excited.

**Comment by meetar** [comment]
Excellent, looks fantastic! Would really like to see how the dev site handles a city upload.

**Comment by robhawkes** [comment]
Me too! I theoretically have all the bits and pieces I need (ie. an account) so I'll try dumping Berlin onto the dev site and see how it goes.

As an aside, it'd be good to get the connection details for accessing the dev database so I can poke around and make sure things are happening as they should be (obviously not in this ticket).

**Comment by robhawkes** [comment]
Ok, I can't actually try this until the dev server is updated to a more recent commit. When that's done I'm ready to push the button to upload the Berlin sample though!

**Comment by bcamper** [comment]
@baldur can't remember where we are with CI/auto-deploy?

**Comment by baldur** [comment]
@bcamper https://circleci.com/gh/polygon-city/building-database ... let me know if you find that it's not operating correctly

**Comment by baldur** [comment]
@bcamper ... sorry hit enter before I was ready ... yes and you can see the status in that link to circle ci

**Comment by robhawkes** [comment]
Cool, that's useful! It shows the right commits but it doesn't seem to be deploying – for example, the latest commit should have changed the "Find a building" link on the homepage from http://dev.polygon.city/browse to http://dev.polygon.city/browse/all (but it's still /browse).

**Comment by robhawkes** [comment]
I noticed the dev server has updated so I've pushed a sample CityGML batch from Berlin for you to see how it looks. There are currently some quirks in the naming, which [I've pushed a fix for](https://github.com/polygon-city/building-database/commit/0fabd97e3f46e4c781fbe4a423e03f1c1b612c14) (though the buildings will need re-uploading / manual updating), as well as a quirk with the rendering of some of the buildings ([which I've opened an issue for](https://github.com/polygon-city/chef-buildingdb/issues/5) in the Chef repo).

**Comment by robhawkes** [comment]
We really have created this at a good time – 3DCityDB [has just been released with CityGML 2.0 support](http://virtualcitysystems.de/en/news/392-new-release-in-3dcitydb-project.html), which is just what I've been waiting for (a lot of the cities are releasing under 2.0). I'm going to give it a few tests later but based on the change-log it should be amazing.

**Comment by robhawkes** [comment]
Going to close this as the relatively new batch uploader functionality combined with [`citygml-to-obj`](https://github.com/polygon-city/citygml-to-obj) and [`building-database-obj-importer`](https://github.com/polygon-city/building-database-obj-importer) implement everything asked for here. There are still some quirks but those can be ironed out in the respective repos.
