### ISSUE TITLE
Segfault on Grunt SASS task after grunt-sass and node-sass upgrades

### ISSUE THREAD

**Issue by robhawkes** [polygon-city/polygon-city-app#94]
Since the `grunt-sass` and `node-sass` upgrades in 3978776ea30c839b6db6ab02b01a931c815c24f8 I've been unable to build the SASS files using Grunt, resulting in a segfault:

```
» DEBUG=polygoncity grunt
Running "clean:server" (clean) task
>> 0 paths cleaned.

Running "sass:dist" (sass) task
[1]    73055 segmentation fault  DEBUG=polygoncity grunt
```

Removing `node-sass` and reverting `grunt-sass` back to 0.16.1 fixes the issue and I can build again.

What was the reason for upgrading `grunt-sass` and adding in `node-sass`? Perhaps we can find an approach that works for both of us if the current method is causing crashes.

**Comment by bcamper** [comment]
I think both @meetar and @baldur were experiencing empty generated CSS files with the old versions, perhaps they can elaborate.

**Comment by bcamper** [comment]
(I didn't experience issues with either version.)

**Comment by meetar** [comment]
@robhawkes We were both seeing the bug mentioned here:

https://github.com/polygon-city/building-database/issues/86#issuecomment-76731342

I don't know that the changes we made are the only possible fix – it just happened to work for us.

**Comment by robhawkes** [comment]
As we discussed in the call, we should see if minor changes to the `node-sass` version (in both directions) have a positive effect for yourself and @baldur. If that also works for me then we can use that for now [until the segfaults have been fixed by `node-sass`](https://github.com/sass/libsass/issues/884) and updated as a `grunt-sass` dependency.

**Comment by baldur** [comment]
@robhawkes node-sass@1.1.4 works with following warnings

Running "sass:dist" (sass) task
WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of node_modules/node-neat/node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss
	from line 30 of public/sass/base/_forms.scss

WARNING: The button mixin is deprecated and will be removed in the next major version release
	on line 64 of node_modules/node-neat/node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss
	from line 355 of public/sass/main.scss

WARNING: The box-sizing mixin is deprecated and will be removed in the next major version release. This property can now be used un-prefixed.
	on line 410 of node_modules/node-neat/node_modules/node-bourbon/node_modules/bourbon/app/assets/stylesheets/_bourbon-deprecated-upcoming.scss
	from line 377 of public/sass/main.scss
	from line 62 of node_modules/node-neat/node_modules/bourbon-neat/app/assets/stylesheets/grid/_media.scss
	from line 371 of public/sass/main.scss

**Comment by robhawkes** [comment]
I still get the segfault with 1.1.4, and even with the latest 3.0.0 beta. What did seem to work was using the master branch of grunt-sass, potentially alone but I did also have `v3.0.0-beta.4` version of node-sass installed too. It seems grunt-sass is the trouble-maker.

Do these work for you too?

**Comment by robhawkes** [comment]
Revisiting this issue…

I've not been seeing any weirdness with `grunt-sass` for a while now – is anyone else still experience issues running the local build process?

**Comment by robhawkes** [comment]
I'm going to close this as I've not heard or seen any issues for a few months now.
